name: build

on:
  push:
    branches: [ "iremssntrk-patch-1" ]
  pull_request:
    branches: [ "iremssntrk-patch-1" ]

jobs:
  start:
    runs-on: windows-latest  
    env:  
       cache-name-codeaster: code-aster-2021-installer
       cache-name-msvc: vcredist-2010-installer
       NUGET_CERT_REVOCATION_MODE: offline
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MsBuild
      uses: microsoft/setup-msbuild@v1.3.1

    # Restore nuget package
    - name: restore-nuget-packages
      run: nuget restore Test.sln
  
    #Build 
    - name: Build
      run: msbuild.exe Test.sln /p:platform="Any CPU" /p:configuration="Debug" /p:Conditionals=GActions

    - name: Enable Cache-code aster
      id: cache-codeaster
      uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\code-aster_v2021_std.msi
        key: ${{ env.cache-name-codeaster }}
        

  FunctionalTest:
    needs: start
    runs-on: windows-latest  
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0


  UnitTest:
    needs: start
    runs-on: windows-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0


    - name: Build
      run: msbuild.exe Test.sln /p:platform="Any CPU" /p:configuration="Debug" /p:Conditionals=GActions
