
name: build

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  start:
    runs-on: windows-latest  
    env:  
       cache-name-codeaster: code-aster-2021-installer
       cache-name-msvc: vcredist-2010-installer
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MsBuild
      uses: microsoft/setup-msbuild@v1.3.1

    # Restore nuget package
    - name: restore-nuget-packages
      run: nuget restore FemBeamAnalyzer.sln
  
    #Build 
    - name: Build
      run: msbuild.exe FemBeamAnalyzer.sln /p:platform="x64" /p:configuration="Debug" /p:Conditionals=GActions


    - name: Enable Cache-code aster
      id: cache-codeaster
      uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\code-aster_v2021_std.msi
        key: ${{ env.cache-name-codeaster }}
        
    
    - name: Install code aster
      if: steps.cache-codeaster.outputs.cache-hit != 'true'
      run : |
            if (Test-Path -Path "C:\Users\runneradmin\AppData\Local\code_aster") {
              echo "code_aster directory exists"  
            } else {
              echo "code_aster directory doesn't exists"
              if(Test-Path -Path "C:\Users\runneradmin\code-aster_v2021_std.msi"){
                echo "code_aster installation file exists"
              } else {  
                # Download the .msi installer (replace with the actual download link)
                echo "code_aster installation file doesn't exists"
                echo "downloading code aster"
                Invoke-WebRequest -Uri "https://simulease.com/wp-content/uploads/2022/02/code-aster_v2021_std.msi" -OutFile "C:\Users\runneradmin\code-aster_v2021_std.msi"
                echo "code aster download completed" 
              }
              echo "installing code aster"
              $args = '/a "C:\Users\runneradmin\code-aster_v2021_std.msi" TARGETDIR="C:\Users\runneradmin\AppData\Local" /quiet'
              Start-Process -Wait -FilePath msiexec -ArgumentList $args -Verb RunAs  
              echo "code aster installation completed" 
              echo "checking code aster installation path"
              if (Test-Path -Path "C:\Users\runneradmin\AppData\Local\code_aster") {
                echo "code_aster directory exists"
                echo "it appears that installation was successfull" 
                echo "updating pyd links for code aster" 
                Start-Process -FilePath "C:\Users\runneradmin\AppData\Local\code_aster\v2021\15.4\update_pyd_links.bat"
                echo "update pyd links for code aster is done" 
              } else {
                echo "code_aster directory doesn't exists"
                echo "it appears that installation was unsuccessfull"
              }
            }  

            
    - name: Enable Cache-msvc
      if: false
      id: cache-msvc
      uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\runneradmin\vcredist_x64.exe
        key: ${{ env.cache-name-msvc }}

    - name: Verify cached file
      run: ls C:\Users\runneradmin\code-aster_v2021_std.msi     

    #Install msvc
    - name: Install msvc
      if: steps.cache-msvc.outputs.cache-hit != 'true'
      run : |
           
            if(Test-Path -Path "C:\Users\runneradmin\vcredist_x64.exe"){
                echo "code_aster installation file exists"
              }
              else{
                Invoke-WebRequest -Uri "https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe" -OutFile "C:\Users\runneradmin\vcredist_x64.exe"
                echo "msvc download completed" 
              }
             
            echo "installing msvc"
            $args = '/a "C:\Users\runneradmin\vcredist_x64.exe" TARGETDIR="C:\Users\runneradmin\AppData\Local" /quiet'
            Start-Process -FilePath "C:\Users\runneradmin\vcredist_x64.exe" 
            echo "msvc installation completed" 


    - name: code aster install check
      run: |
         if(Test-Path -Path "C:\Users\runneradmin\AppData\Local\code_aster"){
                  echo "code_aster installation OK"
                }

   
